search:
  title: software engineer
  locations:
    - Israel
  remote: false
  employment_types:
    - full_time
  experience_levels:
    - entry
filters:
  title:
    include_keywords: ["software", "software engineer", "sw", "swe", "developer", "programmer"]
    exclude_keywords: ["intern", "contract", "student", "senior", "manager", "director", "vp", "principal", "staff", "lead", "qa"]
  location:
    include_keywords: ["Israel", "IL", "Haifa", "Tel Aviv", "Herzliya", "Ramat Gan", "Tel Aviv-Yafo", "Yokne'am Illit"]
spiders:
  microsoft:
    search:
      experience_levels: ["entry", "mid", "senior"]
  meta:
    search:
      locations: ["Tel Aviv, Israel"]
