search:
  title: software engineer
  locations:
    - Israel
  remote: false
  employment_types:
    - full_time
  experience_levels:
    - entry
filters:
  include_keywords: ["software", "software engineer", "sw", "swe", "developer", "programmer"]
  exclude_keywords: ["intern", "contract", "student", "senior", "manager", "director", "vp", "principal", "staff", "lead"]
spiders:
  microsoft:
    search:
      experience_levels: ["entry", "mid", "senior"]
  meta:
    search:
      locations: ["Tel Aviv, Israel"]
