microsoft:
  enabled: true
  url: https://apply.careers.microsoft.com/api/pcsx/search
  headers: {}
  search:
    experience_levels:
      - entry
      - mid

nvidia:
  enabled: true
  url: https://jobs.nvidia.com/api/pcsx/search
  headers: {}
  search:
    experience_levels:
      - entry
      - mid

amazon:
  enabled: true
  url: https://www.amazon.jobs/en/search.json
  headers: {}

apple:
  enabled: true
  url: https://jobs.apple.com/en-il/search
  headers: {}

meta:
  enabled: true
  url: https://www.metacareers.com/jobs
  headers: {}
  search:
    locations:
      - Tel Aviv, Israel

google:
  enabled: true
  url: https://www.google.com/about/careers/applications/jobs/results
  headers: {}