microsoft:
  enabled: true
  url: https://apply.careers.microsoft.com/api/pcsx/search
  headers: {}

nvidia:
  enabled: true
  url: https://jobs.nvidia.com/api/pcsx/search
  headers: {}

amazon:
  enabled: true
  url: https://www.amazon.jobs/en/search.json
  headers: {}

apple:
  enabled: true
  url: https://jobs.apple.com/en-il/search
  headers: {}

meta:
  enabled: true
  url: https://www.metacareers.com/jobs
  headers: {}

google:
  enabled: true
  url: https://www.google.com/about/careers/applications/_/HiringCportalFrontendUi/data/batchexecute
  headers: {}